### PR TITLE
Upstream

### PR DESCRIPTION
**Pull request by cmasone-attic**

### CODE REVIEW

**Comment by cmasone-attic** [comment]
I have no idea if this is the Best Way to bring our fork up to date. Rebasing works fine, actually, in terms of getting our one patch on top of their trunk, but doing it as a PR from my fork of attic-labs/testify leads to a patch that can't be merged to our trunk.

Thoughts?

**Comment by kalman** [comment]
Oh right, yeah, if you look at the original patch I made it was just deleting a bunch of code.

I don't know what I'm looking at though; is it a merge? a rebase?

**Comment by aboodman** [comment]
Is now a good time to consider reimplementing the few parts of tesitfy we
use?

**Comment by kalman** [comment]
That's what I was thinking, though I don't mind volunteering for this. It
just depends on timing.

**Comment by kalman** [comment]
as in, whether I do it depends on whether that should block this patch,
and/or block Chris.

**Comment by cmasone-attic** [comment]
This is a big merge.

I'm updating because, in our current fork there's an issue where errors generated inside test cases that use the go 1.7 `t.Run()` stuff have bogus stacks. It's been fixed in ToT. I could just cherry-pick that patch over. I could rebase our one patch that removes the HTTP stuff on top of their ToT and just rewrite history here in our fork. Or, I could land this merge. I'm fine with any of these choices, but I would like to resolve this bug sooner rather than later.

**Comment by kalman** [comment]
Let's just merge this and remove the testify fork in a follow up (which I'm happy to do).

**Comment by aboodman** [comment]
lgtm

**Pull request merged**
